import 'club_identity.dart';

/// Curated legal-safe identity metadata keyed by normalized slug.
abstract final class ClubIdentityData {
  static const Map<String, ClubIdentity> bySlug = {
    // Spain
    'fc-barcelona': ClubIdentity(
      primaryColor: '#A50044',
      secondaryColor: '#004D98',
      accentColor: '#FFD700',
      symbolType: ClubSymbolType.abstractStripes,
      shortCode: 'BAR',
      badgeStyle: ClubBadgeStyle.vertical,
    ),
    'barcelona': ClubIdentity(
      primaryColor: '#A50044',
      secondaryColor: '#004D98',
      accentColor: '#FFD700',
      symbolType: ClubSymbolType.abstractStripes,
      shortCode: 'BAR',
      badgeStyle: ClubBadgeStyle.vertical,
    ),
    'real-madrid': ClubIdentity(
      primaryColor: '#F5F5F5',
      secondaryColor: '#FEBE10',
      accentColor: '#C0C0C0',
      symbolType: ClubSymbolType.abstractCrown,
      shortCode: 'RMA',
      badgeStyle: ClubBadgeStyle.metallic,
    ),
    'atletico-madrid': ClubIdentity(
      primaryColor: '#CB3524',
      secondaryColor: '#FFFFFF',
      accentColor: '#1A3A6B',
      symbolType: ClubSymbolType.abstractWaves,
      shortCode: 'ATM',
      badgeStyle: ClubBadgeStyle.vertical,
    ),
    'sevilla-fc': ClubIdentity(
      primaryColor: '#FFFFFF',
      secondaryColor: '#D50000',
      accentColor: '#FFD700',
      symbolType: ClubSymbolType.abstractCross,
      shortCode: 'SEV',
      badgeStyle: ClubBadgeStyle.horizontal,
    ),
    'valencia-cf': ClubIdentity(
      primaryColor: '#EE3524',
      secondaryColor: '#000000',
      accentColor: '#FF8C00',
      symbolType: ClubSymbolType.abstractDiamond,
      shortCode: 'VAL',
      badgeStyle: ClubBadgeStyle.vertical,
    ),
    // England
    'chelsea': ClubIdentity(
      primaryColor: '#034694',
      secondaryColor: '#FFFFFF',
      accentColor: '#FFD700',
      symbolType: ClubSymbolType.abstractLion,
      shortCode: 'CHE',
      badgeStyle: ClubBadgeStyle.metallic,
    ),
    'chelsea-fc': ClubIdentity(
      primaryColor: '#034694',
      secondaryColor: '#FFFFFF',
      accentColor: '#FFD700',
      symbolType: ClubSymbolType.abstractLion,
      shortCode: 'CHE',
      badgeStyle: ClubBadgeStyle.metallic,
    ),
    'manchester-united': ClubIdentity(
      primaryColor: '#DA291C',
      secondaryColor: '#FBE122',
      accentColor: '#000000',
      symbolType: ClubSymbolType.abstractOrb,
      shortCode: 'MUN',
      badgeStyle: ClubBadgeStyle.vertical,
    ),
    'manchester-city': ClubIdentity(
      primaryColor: '#6CABDD',
      secondaryColor: '#FFFFFF',
      accentColor: '#1C2C5B',
      symbolType: ClubSymbolType.abstractCompass,
      shortCode: 'MCI',
      badgeStyle: ClubBadgeStyle.radial,
    ),
    'liverpool-fc': ClubIdentity(
      primaryColor: '#C8102E',
      secondaryColor: '#FFFFFF',
      accentColor: '#FFD700',
      symbolType: ClubSymbolType.abstractWings,
      shortCode: 'LIV',
      badgeStyle: ClubBadgeStyle.vertical,
    ),
    'arsenal-fc': ClubIdentity(
      primaryColor: '#EF0107',
      secondaryColor: '#FFFFFF',
      accentColor: '#FFD700',
      symbolType: ClubSymbolType.abstractChevron,
      shortCode: 'ARS',
      badgeStyle: ClubBadgeStyle.vertical,
    ),
    'tottenham-hotspur': ClubIdentity(
      primaryColor: '#132257',
      secondaryColor: '#FFFFFF',
      accentColor: '#C0C0C0',
      symbolType: ClubSymbolType.abstractStar,
      shortCode: 'TOT',
      badgeStyle: ClubBadgeStyle.vertical,
    ),
    'newcastle-united': ClubIdentity(
      primaryColor: '#241F20',
      secondaryColor: '#FFFFFF',
      accentColor: '#888888',
      symbolType: ClubSymbolType.abstractStar,
      shortCode: 'NEW',
      badgeStyle: ClubBadgeStyle.vertical,
    ),
    'west-ham-united': ClubIdentity(
      primaryColor: '#7A263A',
      secondaryColor: '#1BB1E7',
      accentColor: '#FFD700',
      symbolType: ClubSymbolType.abstractCross,
      shortCode: 'WHU',
      badgeStyle: ClubBadgeStyle.vertical,
    ),
    'aston-villa': ClubIdentity(
      primaryColor: '#670E36',
      secondaryColor: '#95BFE5',
      accentColor: '#FFD700',
      symbolType: ClubSymbolType.abstractStar,
      shortCode: 'AVL',
      badgeStyle: ClubBadgeStyle.vertical,
    ),
    'everton-fc': ClubIdentity(
      primaryColor: '#003399',
      secondaryColor: '#FFFFFF',
      accentColor: '#FFD700',
      symbolType: ClubSymbolType.abstractChevron,
      shortCode: 'EVE',
      badgeStyle: ClubBadgeStyle.vertical,
    ),
    // Germany
    'bayern-munich': ClubIdentity(
      primaryColor: '#DC052D',
      secondaryColor: '#0066B2',
      accentColor: '#FFFFFF',
      symbolType: ClubSymbolType.abstractDiamond,
      shortCode: 'BAY',
      badgeStyle: ClubBadgeStyle.vertical,
    ),
    'borussia-dortmund': ClubIdentity(
      primaryColor: '#FDE100',
      secondaryColor: '#000000',
      accentColor: '#FFFFFF',
      symbolType: ClubSymbolType.abstractStripes,
      shortCode: 'BVB',
      badgeStyle: ClubBadgeStyle.horizontal,
    ),
    'rb-leipzig': ClubIdentity(
      primaryColor: '#DD0741',
      secondaryColor: '#FFFFFF',
      accentColor: '#002D5C',
      symbolType: ClubSymbolType.abstractOrb,
      shortCode: 'RBL',
      badgeStyle: ClubBadgeStyle.vertical,
    ),
    'bayer-leverkusen': ClubIdentity(
      primaryColor: '#E32221',
      secondaryColor: '#000000',
      accentColor: '#FFFFFF',
      symbolType: ClubSymbolType.abstractCross,
      shortCode: 'B04',
      badgeStyle: ClubBadgeStyle.vertical,
    ),
    'borussia-monchengladbach': ClubIdentity(
      primaryColor: '#000000',
      secondaryColor: '#FFFFFF',
      accentColor: '#1F6841',
      symbolType: ClubSymbolType.abstractDiamond,
      shortCode: 'BMG',
      badgeStyle: ClubBadgeStyle.vertical,
    ),
    // Italy
    'juventus': ClubIdentity(
      primaryColor: '#000000',
      secondaryColor: '#FFFFFF',
      accentColor: '#C0C0C0',
      symbolType: ClubSymbolType.abstractChevron,
      shortCode: 'JUV',
      badgeStyle: ClubBadgeStyle.metallic,
    ),
    'ac-milan': ClubIdentity(
      primaryColor: '#FB090B',
      secondaryColor: '#000000',
      accentColor: '#FFFFFF',
      symbolType: ClubSymbolType.abstractCross,
      shortCode: 'MIL',
      badgeStyle: ClubBadgeStyle.vertical,
    ),
    'inter-milan': ClubIdentity(
      primaryColor: '#010E80',
      secondaryColor: '#000000',
      accentColor: '#FFD700',
      symbolType: ClubSymbolType.abstractOrb,
      shortCode: 'INT',
      badgeStyle: ClubBadgeStyle.vertical,
    ),
    'as-roma': ClubIdentity(
      primaryColor: '#8E1F2F',
      secondaryColor: '#F0BC42',
      accentColor: '#FFD700',
      symbolType: ClubSymbolType.abstractFlame,
      shortCode: 'ROM',
      badgeStyle: ClubBadgeStyle.vertical,
    ),
    'napoli': ClubIdentity(
      primaryColor: '#12A0D7',
      secondaryColor: '#FFFFFF',
      accentColor: '#FFD700',
      symbolType: ClubSymbolType.abstractWaves,
      shortCode: 'NAP',
      badgeStyle: ClubBadgeStyle.radial,
    ),
    'lazio': ClubIdentity(
      primaryColor: '#87D8F7',
      secondaryColor: '#FFFFFF',
      accentColor: '#FFD700',
      symbolType: ClubSymbolType.abstractWaves,
      shortCode: 'LAZ',
      badgeStyle: ClubBadgeStyle.vertical,
    ),
    'fiorentina': ClubIdentity(
      primaryColor: '#482E92',
      secondaryColor: '#FFFFFF',
      accentColor: '#FFD700',
      symbolType: ClubSymbolType.abstractFlame,
      shortCode: 'FIO',
      badgeStyle: ClubBadgeStyle.vertical,
    ),
    // France
    'paris-saintgermain': ClubIdentity(
      primaryColor: '#004170',
      secondaryColor: '#DA020E',
      accentColor: '#FFD700',
      symbolType: ClubSymbolType.abstractOrb,
      shortCode: 'PSG',
      badgeStyle: ClubBadgeStyle.metallic,
    ),
    'psg': ClubIdentity(
      primaryColor: '#004170',
      secondaryColor: '#DA020E',
      accentColor: '#FFD700',
      symbolType: ClubSymbolType.abstractOrb,
      shortCode: 'PSG',
      badgeStyle: ClubBadgeStyle.metallic,
    ),
    'lyon': ClubIdentity(
      primaryColor: '#103889',
      secondaryColor: '#DA020E',
      accentColor: '#FFFFFF',
      symbolType: ClubSymbolType.abstractLion,
      shortCode: 'OL',
      badgeStyle: ClubBadgeStyle.vertical,
    ),
    'marseille': ClubIdentity(
      primaryColor: '#2FAEE0',
      secondaryColor: '#FFFFFF',
      accentColor: '#FFD700',
      symbolType: ClubSymbolType.abstractStar,
      shortCode: 'OM',
      badgeStyle: ClubBadgeStyle.radial,
    ),
    'monaco': ClubIdentity(
      primaryColor: '#E30613',
      secondaryColor: '#FFFFFF',
      accentColor: '#FFD700',
      symbolType: ClubSymbolType.abstractCrown,
      shortCode: 'MON',
      badgeStyle: ClubBadgeStyle.metallic,
    ),
    'lille-osc': ClubIdentity(
      primaryColor: '#E01E13',
      secondaryColor: '#FFFFFF',
      accentColor: '#002D5C',
      symbolType: ClubSymbolType.abstractOrb,
      shortCode: 'LIL',
      badgeStyle: ClubBadgeStyle.vertical,
    ),
    // Turkey
    'galatasaray': ClubIdentity(
      primaryColor: '#FDB912',
      secondaryColor: '#A90432',
      accentColor: '#FFD700',
      symbolType: ClubSymbolType.abstractLion,
      shortCode: 'GAL',
      badgeStyle: ClubBadgeStyle.vertical,
    ),
    'fenerbahce': ClubIdentity(
      primaryColor: '#FFED00',
      secondaryColor: '#00205B',
      accentColor: '#FFFFFF',
      symbolType: ClubSymbolType.abstractOak,
      shortCode: 'FEN',
      badgeStyle: ClubBadgeStyle.horizontal,
    ),
    'besiktas': ClubIdentity(
      primaryColor: '#000000',
      secondaryColor: '#FFFFFF',
      accentColor: '#FFD700',
      symbolType: ClubSymbolType.abstractEagle,
      shortCode: 'BJK',
      badgeStyle: ClubBadgeStyle.vertical,
    ),
    'trabzonspor': ClubIdentity(
      primaryColor: '#7B002C',
      secondaryColor: '#0072BC',
      accentColor: '#FFD700',
      symbolType: ClubSymbolType.abstractWaves,
      shortCode: 'TRA',
      badgeStyle: ClubBadgeStyle.vertical,
    ),
    // Netherlands / Portugal
    'ajax': ClubIdentity(
      primaryColor: '#D2122E',
      secondaryColor: '#FFFFFF',
      accentColor: '#FFD700',
      symbolType: ClubSymbolType.abstractOrb,
      shortCode: 'AJA',
      badgeStyle: ClubBadgeStyle.vertical,
    ),
    'psv-eindhoven': ClubIdentity(
      primaryColor: '#ED1C24',
      secondaryColor: '#FFFFFF',
      accentColor: '#FFD700',
      symbolType: ClubSymbolType.abstractStripes,
      shortCode: 'PSV',
      badgeStyle: ClubBadgeStyle.vertical,
    ),
    'feyenoord': ClubIdentity(
      primaryColor: '#FF0000',
      secondaryColor: '#FFFFFF',
      accentColor: '#000000',
      symbolType: ClubSymbolType.abstractOrb,
      shortCode: 'FEY',
      badgeStyle: ClubBadgeStyle.vertical,
    ),
    'benfica': ClubIdentity(
      primaryColor: '#FF0000',
      secondaryColor: '#FFFFFF',
      accentColor: '#FFD700',
      symbolType: ClubSymbolType.abstractWaves,
      shortCode: 'BEN',
      badgeStyle: ClubBadgeStyle.vertical,
    ),
    'fc-porto': ClubIdentity(
      primaryColor: '#003893',
      secondaryColor: '#FFFFFF',
      accentColor: '#FFD700',
      symbolType: ClubSymbolType.abstractFlame,
      shortCode: 'POR',
      badgeStyle: ClubBadgeStyle.vertical,
    ),
    'sporting-cp': ClubIdentity(
      primaryColor: '#008057',
      secondaryColor: '#FFFFFF',
      accentColor: '#FFD700',
      symbolType: ClubSymbolType.abstractLion,
      shortCode: 'SCP',
      badgeStyle: ClubBadgeStyle.vertical,
    ),
    // Scotland / Americas
    'celtic-fc': ClubIdentity(
      primaryColor: '#008050',
      secondaryColor: '#FFFFFF',
      accentColor: '#FFD700',
      symbolType: ClubSymbolType.abstractCross,
      shortCode: 'CEL',
      badgeStyle: ClubBadgeStyle.vertical,
    ),
    'rangers-fc': ClubIdentity(
      primaryColor: '#1B458F',
      secondaryColor: '#FFFFFF',
      accentColor: '#FFD700',
      symbolType: ClubSymbolType.abstractStar,
      shortCode: 'RAN',
      badgeStyle: ClubBadgeStyle.vertical,
    ),
    'river-plate': ClubIdentity(
      primaryColor: '#FFFFFF',
      secondaryColor: '#ED1C24',
      accentColor: '#FFD700',
      symbolType: ClubSymbolType.abstractWaves,
      shortCode: 'RIV',
      badgeStyle: ClubBadgeStyle.horizontal,
    ),
    'boca-juniors': ClubIdentity(
      primaryColor: '#003087',
      secondaryColor: '#FCB131',
      accentColor: '#FFFFFF',
      symbolType: ClubSymbolType.abstractWaves,
      shortCode: 'BOC',
      badgeStyle: ClubBadgeStyle.horizontal,
    ),
    'flamengo': ClubIdentity(
      primaryColor: '#C3281E',
      secondaryColor: '#000000',
      accentColor: '#FFFFFF',
      symbolType: ClubSymbolType.abstractStripes,
      shortCode: 'FLA',
      badgeStyle: ClubBadgeStyle.vertical,
    ),
    'palmeiras': ClubIdentity(
      primaryColor: '#006437',
      secondaryColor: '#FFFFFF',
      accentColor: '#FFD700',
      symbolType: ClubSymbolType.abstractDiamond,
      shortCode: 'PAL',
      badgeStyle: ClubBadgeStyle.vertical,
    ),
    'santos-fc': ClubIdentity(
      primaryColor: '#FFFFFF',
      secondaryColor: '#000000',
      accentColor: '#FFD700',
      symbolType: ClubSymbolType.abstractOrb,
      shortCode: 'SAN',
      badgeStyle: ClubBadgeStyle.horizontal,
    ),
    'corinthians': ClubIdentity(
      primaryColor: '#000000',
      secondaryColor: '#FFFFFF',
      accentColor: '#FFD700',
      symbolType: ClubSymbolType.abstractOrb,
      shortCode: 'COR',
      badgeStyle: ClubBadgeStyle.vertical,
    ),
    'inter-miami': ClubIdentity(
      primaryColor: '#F7B5CD',
      secondaryColor: '#000000',
      accentColor: '#FFFFFF',
      symbolType: ClubSymbolType.abstractWaves,
      shortCode: 'MIA',
      badgeStyle: ClubBadgeStyle.radial,
    ),
    'la-galaxy': ClubIdentity(
      primaryColor: '#00245D',
      secondaryColor: '#FFD200',
      accentColor: '#FFFFFF',
      symbolType: ClubSymbolType.abstractStar,
      shortCode: 'LAG',
      badgeStyle: ClubBadgeStyle.vertical,
    ),
    // Middle East / Asia / Africa — abstract defaults
    'al-hilal': ClubIdentity(
      primaryColor: '#004AAC',
      secondaryColor: '#FFFFFF',
      accentColor: '#FFD700',
      symbolType: ClubSymbolType.abstractOrb,
      shortCode: 'HIL',
      badgeStyle: ClubBadgeStyle.metallic,
    ),
    'al-nassr': ClubIdentity(
      primaryColor: '#FEDC00',
      secondaryColor: '#0E4D92',
      accentColor: '#FFFFFF',
      symbolType: ClubSymbolType.abstractStar,
      shortCode: 'NSR',
      badgeStyle: ClubBadgeStyle.vertical,
    ),
    'al-ahli': ClubIdentity(
      primaryColor: '#00783E',
      secondaryColor: '#FFFFFF',
      accentColor: '#FFD700',
      symbolType: ClubSymbolType.abstractStar,
      shortCode: 'AHL',
      badgeStyle: ClubBadgeStyle.vertical,
    ),
    'al-ahly-cairo': ClubIdentity(
      primaryColor: '#E60012',
      secondaryColor: '#FFFFFF',
      accentColor: '#FFD700',
      symbolType: ClubSymbolType.abstractWaves,
      shortCode: 'AHL',
      badgeStyle: ClubBadgeStyle.vertical,
    ),
    // Europe — remaining curated identities
    'aik': ClubIdentity(
      primaryColor: '#000000',
      secondaryColor: '#FFEC00',
      accentColor: '#FFFFFF',
      symbolType: ClubSymbolType.abstractStripes,
      shortCode: 'AIK',
      badgeStyle: ClubBadgeStyle.vertical,
    ),
    'anderlecht': ClubIdentity(
      primaryColor: '#4B0082',
      secondaryColor: '#FFFFFF',
      accentColor: '#FFD700',
      symbolType: ClubSymbolType.abstractDiamond,
      shortCode: 'AND',
      badgeStyle: ClubBadgeStyle.vertical,
    ),
    'apoel': ClubIdentity(
      primaryColor: '#FFD700',
      secondaryColor: '#004799',
      accentColor: '#FFFFFF',
      symbolType: ClubSymbolType.abstractCross,
      shortCode: 'APO',
      badgeStyle: ClubBadgeStyle.vertical,
    ),
    'basel': ClubIdentity(
      primaryColor: '#FF0000',
      secondaryColor: '#0000FF',
      accentColor: '#FFFFFF',
      symbolType: ClubSymbolType.abstractCross,
      shortCode: 'BAS',
      badgeStyle: ClubBadgeStyle.vertical,
    ),
    'brondby': ClubIdentity(
      primaryColor: '#FFDD00',
      secondaryColor: '#0066B3',
      accentColor: '#FFFFFF',
      symbolType: ClubSymbolType.abstractWaves,
      shortCode: 'BIF',
      badgeStyle: ClubBadgeStyle.vertical,
    ),
    'cfr-cluj': ClubIdentity(
      primaryColor: '#FF6600',
      secondaryColor: '#000000',
      accentColor: '#FFD700',
      symbolType: ClubSymbolType.abstractFlame,
      shortCode: 'CFR',
      badgeStyle: ClubBadgeStyle.vertical,
    ),
    'club-brugge': ClubIdentity(
      primaryColor: '#0080C8',
      secondaryColor: '#000000',
      accentColor: '#FFD700',
      symbolType: ClubSymbolType.abstractDiamond,
      shortCode: 'BRU',
      badgeStyle: ClubBadgeStyle.vertical,
    ),
    'copenhagen': ClubIdentity(
      primaryColor: '#0054A6',
      secondaryColor: '#FFFFFF',
      accentColor: '#FFD700',
      symbolType: ClubSymbolType.abstractWaves,
      shortCode: 'FCK',
      badgeStyle: ClubBadgeStyle.radial,
    ),
    'dinamo-zagreb': ClubIdentity(
      primaryColor: '#0057B8',
      secondaryColor: '#FFFFFF',
      accentColor: '#FFD700',
      symbolType: ClubSymbolType.abstractChevron,
      shortCode: 'DIN',
      badgeStyle: ClubBadgeStyle.vertical,
    ),
    'dynamo-kyiv': ClubIdentity(
      primaryColor: '#0457A6',
      secondaryColor: '#FFFFFF',
      accentColor: '#FFD700',
      symbolType: ClubSymbolType.abstractStar,
      shortCode: 'DYN',
      badgeStyle: ClubBadgeStyle.vertical,
    ),
    'hajduk-split': ClubIdentity(
      primaryColor: '#FFFFFF',
      secondaryColor: '#004B87',
      accentColor: '#FFD700',
      symbolType: ClubSymbolType.abstractWaves,
      shortCode: 'HAJ',
      badgeStyle: ClubBadgeStyle.horizontal,
    ),
    'hjk-helsinki': ClubIdentity(
      primaryColor: '#0066CC',
      secondaryColor: '#FFFFFF',
      accentColor: '#FFD700',
      symbolType: ClubSymbolType.abstractCross,
      shortCode: 'HJK',
      badgeStyle: ClubBadgeStyle.vertical,
    ),
    'legia-warsaw': ClubIdentity(
      primaryColor: '#007A33',
      secondaryColor: '#FFFFFF',
      accentColor: '#FFD700',
      symbolType: ClubSymbolType.abstractEagle,
      shortCode: 'LEG',
      badgeStyle: ClubBadgeStyle.vertical,
    ),
    'malmo-ff': ClubIdentity(
      primaryColor: '#79BFEF',
      secondaryColor: '#FFFFFF',
      accentColor: '#004799',
      symbolType: ClubSymbolType.abstractWaves,
      shortCode: 'MFF',
      badgeStyle: ClubBadgeStyle.vertical,
    ),
    'molde-fk': ClubIdentity(
      primaryColor: '#0054A0',
      secondaryColor: '#FFFFFF',
      accentColor: '#FFD700',
      symbolType: ClubSymbolType.abstractWaves,
      shortCode: 'MOL',
      badgeStyle: ClubBadgeStyle.vertical,
    ),
    'olympiacos': ClubIdentity(
      primaryColor: '#E30613',
      secondaryColor: '#FFFFFF',
      accentColor: '#FFD700',
      symbolType: ClubSymbolType.abstractFlame,
      shortCode: 'OLY',
      badgeStyle: ClubBadgeStyle.vertical,
    ),
    'omonia': ClubIdentity(
      primaryColor: '#007A33',
      secondaryColor: '#FFFFFF',
      accentColor: '#FFD700',
      symbolType: ClubSymbolType.abstractOrb,
      shortCode: 'OMO',
      badgeStyle: ClubBadgeStyle.vertical,
    ),
    'panathinaikos': ClubIdentity(
      primaryColor: '#009B4B',
      secondaryColor: '#FFFFFF',
      accentColor: '#FFD700',
      symbolType: ClubSymbolType.abstractOak,
      shortCode: 'PAO',
      badgeStyle: ClubBadgeStyle.vertical,
    ),
    'partizan': ClubIdentity(
      primaryColor: '#000000',
      secondaryColor: '#FFFFFF',
      accentColor: '#FFD700',
      symbolType: ClubSymbolType.abstractStripes,
      shortCode: 'PAR',
      badgeStyle: ClubBadgeStyle.vertical,
    ),
    'qarabag-fk': ClubIdentity(
      primaryColor: '#000000',
      secondaryColor: '#FFFFFF',
      accentColor: '#FFD700',
      symbolType: ClubSymbolType.abstractDiamond,
      shortCode: 'QAR',
      badgeStyle: ClubBadgeStyle.metallic,
    ),
    'rapid-vienna': ClubIdentity(
      primaryColor: '#007A33',
      secondaryColor: '#FFFFFF',
      accentColor: '#FFD700',
      symbolType: ClubSymbolType.abstractFlame,
      shortCode: 'RAP',
      badgeStyle: ClubBadgeStyle.vertical,
    ),
    'red-star-belgrade': ClubIdentity(
      primaryColor: '#D6000F',
      secondaryColor: '#FFFFFF',
      accentColor: '#FFD700',
      symbolType: ClubSymbolType.abstractStar,
      shortCode: 'RSB',
      badgeStyle: ClubBadgeStyle.vertical,
    ),
    'rosenborg': ClubIdentity(
      primaryColor: '#000000',
      secondaryColor: '#FFFFFF',
      accentColor: '#FFD700',
      symbolType: ClubSymbolType.abstractCrown,
      shortCode: 'RBK',
      badgeStyle: ClubBadgeStyle.vertical,
    ),
    'salzburg': ClubIdentity(
      primaryColor: '#E30613',
      secondaryColor: '#FFFFFF',
      accentColor: '#FFD700',
      symbolType: ClubSymbolType.abstractDiamond,
      shortCode: 'RBS',
      badgeStyle: ClubBadgeStyle.metallic,
    ),
    'shakhtar-donetsk': ClubIdentity(
      primaryColor: '#FF7800',
      secondaryColor: '#000000',
      accentColor: '#FFD700',
      symbolType: ClubSymbolType.abstractFlame,
      shortCode: 'SHA',
      badgeStyle: ClubBadgeStyle.vertical,
    ),
    'slavia-prague': ClubIdentity(
      primaryColor: '#E30613',
      secondaryColor: '#FFFFFF',
      accentColor: '#FFD700',
      symbolType: ClubSymbolType.abstractLion,
      shortCode: 'SLA',
      badgeStyle: ClubBadgeStyle.vertical,
    ),
    'sparta-prague': ClubIdentity(
      primaryColor: '#8B002E',
      secondaryColor: '#FFFFFF',
      accentColor: '#FFD700',
      symbolType: ClubSymbolType.abstractChevron,
      shortCode: 'SPA',
      badgeStyle: ClubBadgeStyle.vertical,
    ),
    'steaua-bucharest': ClubIdentity(
      primaryColor: '#0066CC',
      secondaryColor: '#CC0000',
      accentColor: '#FFD700',
      symbolType: ClubSymbolType.abstractStar,
      shortCode: 'STE',
      badgeStyle: ClubBadgeStyle.radial,
    ),
    'young-boys': ClubIdentity(
      primaryColor: '#FFDD00',
      secondaryColor: '#000000',
      accentColor: '#FFFFFF',
      symbolType: ClubSymbolType.abstractStripes,
      shortCode: 'YB',
      badgeStyle: ClubBadgeStyle.horizontal,
    ),
    // Americas
    'club-america': ClubIdentity(
      primaryColor: '#FBCC17',
      secondaryColor: '#00265D',
      accentColor: '#FFFFFF',
      symbolType: ClubSymbolType.abstractEagle,
      shortCode: 'AME',
      badgeStyle: ClubBadgeStyle.vertical,
    ),
    'monterrey': ClubIdentity(
      primaryColor: '#004481',
      secondaryColor: '#FFFFFF',
      accentColor: '#FFD700',
      symbolType: ClubSymbolType.abstractDiamond,
      shortCode: 'MTY',
      badgeStyle: ClubBadgeStyle.vertical,
    ),
    // Asia-Pacific
    'guangzhou-fc': ClubIdentity(
      primaryColor: '#E60012',
      secondaryColor: '#FFFFFF',
      accentColor: '#FFD700',
      symbolType: ClubSymbolType.abstractFlame,
      shortCode: 'GZ',
      badgeStyle: ClubBadgeStyle.vertical,
    ),
    'shanghai-sipg': ClubIdentity(
      primaryColor: '#E60012',
      secondaryColor: '#FFFFFF',
      accentColor: '#FFD700',
      symbolType: ClubSymbolType.abstractCompass,
      shortCode: 'SIP',
      badgeStyle: ClubBadgeStyle.vertical,
    ),
    'kashima-antlers': ClubIdentity(
      primaryColor: '#E60012',
      secondaryColor: '#0055A4',
      accentColor: '#FFFFFF',
      symbolType: ClubSymbolType.abstractChevron,
      shortCode: 'KAS',
      badgeStyle: ClubBadgeStyle.vertical,
    ),
    'urawa-red-diamonds': ClubIdentity(
      primaryColor: '#E60012',
      secondaryColor: '#FFFFFF',
      accentColor: '#FFD700',
      symbolType: ClubSymbolType.abstractDiamond,
      shortCode: 'URA',
      badgeStyle: ClubBadgeStyle.vertical,
    ),
    'jeonbuk-hyundai': ClubIdentity(
      primaryColor: '#006633',
      secondaryColor: '#FFFFFF',
      accentColor: '#FFD700',
      symbolType: ClubSymbolType.abstractStripes,
      shortCode: 'JHM',
      badgeStyle: ClubBadgeStyle.vertical,
    ),
    'ulsan-hd': ClubIdentity(
      primaryColor: '#004689',
      secondaryColor: '#F5A623',
      accentColor: '#FFFFFF',
      symbolType: ClubSymbolType.abstractCompass,
      shortCode: 'ULS',
      badgeStyle: ClubBadgeStyle.vertical,
    ),
    'sydney-fc': ClubIdentity(
      primaryColor: '#88C5EE',
      secondaryColor: '#FFFFFF',
      accentColor: '#004799',
      symbolType: ClubSymbolType.abstractWaves,
      shortCode: 'SYD',
      badgeStyle: ClubBadgeStyle.radial,
    ),
    'melbourne-city': ClubIdentity(
      primaryColor: '#6CACDE',
      secondaryColor: '#FFFFFF',
      accentColor: '#FFD700',
      symbolType: ClubSymbolType.abstractCompass,
      shortCode: 'MCY',
      badgeStyle: ClubBadgeStyle.vertical,
    ),
    // Africa & Middle East
    'esperance-tunis': ClubIdentity(
      primaryColor: '#FFD700',
      secondaryColor: '#E60012',
      accentColor: '#FFFFFF',
      symbolType: ClubSymbolType.abstractStar,
      shortCode: 'EST',
      badgeStyle: ClubBadgeStyle.metallic,
    ),
    'raja-casablanca': ClubIdentity(
      primaryColor: '#007A33',
      secondaryColor: '#FFFFFF',
      accentColor: '#FFD700',
      symbolType: ClubSymbolType.abstractStar,
      shortCode: 'RAJ',
      badgeStyle: ClubBadgeStyle.vertical,
    ),
    'wydad-ac': ClubIdentity(
      primaryColor: '#E60012',
      secondaryColor: '#FFFFFF',
      accentColor: '#FFD700',
      symbolType: ClubSymbolType.abstractFlame,
      shortCode: 'WAC',
      badgeStyle: ClubBadgeStyle.vertical,
    ),
    'maccabi-tel-aviv': ClubIdentity(
      primaryColor: '#FEDD00',
      secondaryColor: '#004899',
      accentColor: '#FFFFFF',
      symbolType: ClubSymbolType.abstractStar,
      shortCode: 'MTA',
      badgeStyle: ClubBadgeStyle.vertical,
    ),
    'maccabi-haifa': ClubIdentity(
      primaryColor: '#007A33',
      secondaryColor: '#FFFFFF',
      accentColor: '#FFD700',
      symbolType: ClubSymbolType.abstractStar,
      shortCode: 'MHA',
      badgeStyle: ClubBadgeStyle.vertical,
    ),
    'kaizer-chiefs': ClubIdentity(
      primaryColor: '#FFB612',
      secondaryColor: '#000000',
      accentColor: '#FFFFFF',
      symbolType: ClubSymbolType.abstractCrown,
      shortCode: 'KAI',
      badgeStyle: ClubBadgeStyle.metallic,
    ),
    'orlando-pirates': ClubIdentity(
      primaryColor: '#000000',
      secondaryColor: '#FFFFFF',
      accentColor: '#FFD700',
      symbolType: ClubSymbolType.abstractWaves,
      shortCode: 'PIR',
      badgeStyle: ClubBadgeStyle.vertical,
    ),
  };
}
