import 'club_identity.dart';

/// Curated legal-safe identity metadata keyed by normalized slug.
abstract final class ClubIdentityData {
  static const Map<String, ClubIdentity> bySlug = {
    // Spain
    'fc-barcelona': ClubIdentity(
      primaryColor: '#A50044',
      secondaryColor: '#004D98',
      accentColor: '#FFD700',
      symbolType: ClubSymbolType.abstractStripes,
      shortCode: 'BAR',
      badgeStyle: ClubBadgeStyle.vertical,
    ),
    'barcelona': ClubIdentity(
      primaryColor: '#A50044',
      secondaryColor: '#004D98',
      accentColor: '#FFD700',
      symbolType: ClubSymbolType.abstractStripes,
      shortCode: 'BAR',
      badgeStyle: ClubBadgeStyle.vertical,
    ),
    'real-madrid': ClubIdentity(
      primaryColor: '#F5F5F5',
      secondaryColor: '#FEBE10',
      accentColor: '#C0C0C0',
      symbolType: ClubSymbolType.abstractCrown,
      shortCode: 'RMA',
      badgeStyle: ClubBadgeStyle.metallic,
    ),
    'atletico-madrid': ClubIdentity(
      primaryColor: '#CB3524',
      secondaryColor: '#FFFFFF',
      accentColor: '#1A3A6B',
      symbolType: ClubSymbolType.abstractWaves,
      shortCode: 'ATM',
      badgeStyle: ClubBadgeStyle.vertical,
    ),
    'sevilla-fc': ClubIdentity(
      primaryColor: '#FFFFFF',
      secondaryColor: '#D50000',
      accentColor: '#FFD700',
      symbolType: ClubSymbolType.abstractCross,
      shortCode: 'SEV',
      badgeStyle: ClubBadgeStyle.horizontal,
    ),
    'valencia-cf': ClubIdentity(
      primaryColor: '#EE3524',
      secondaryColor: '#000000',
      accentColor: '#FF8C00',
      symbolType: ClubSymbolType.abstractDiamond,
      shortCode: 'VAL',
      badgeStyle: ClubBadgeStyle.vertical,
    ),
    // England
    'chelsea': ClubIdentity(
      primaryColor: '#034694',
      secondaryColor: '#FFFFFF',
      accentColor: '#FFD700',
      symbolType: ClubSymbolType.abstractLion,
      shortCode: 'CHE',
      badgeStyle: ClubBadgeStyle.metallic,
    ),
    'chelsea-fc': ClubIdentity(
      primaryColor: '#034694',
      secondaryColor: '#FFFFFF',
      accentColor: '#FFD700',
      symbolType: ClubSymbolType.abstractLion,
      shortCode: 'CHE',
      badgeStyle: ClubBadgeStyle.metallic,
    ),
    'manchester-united': ClubIdentity(
      primaryColor: '#DA291C',
      secondaryColor: '#FBE122',
      accentColor: '#000000',
      symbolType: ClubSymbolType.abstractOrb,
      shortCode: 'MUN',
      badgeStyle: ClubBadgeStyle.vertical,
    ),
    'manchester-city': ClubIdentity(
      primaryColor: '#6CABDD',
      secondaryColor: '#FFFFFF',
      accentColor: '#1C2C5B',
      symbolType: ClubSymbolType.abstractShield,
      shortCode: 'MCI',
      badgeStyle: ClubBadgeStyle.radial,
    ),
    'liverpool-fc': ClubIdentity(
      primaryColor: '#C8102E',
      secondaryColor: '#FFFFFF',
      accentColor: '#FFD700',
      symbolType: ClubSymbolType.abstractFlame,
      shortCode: 'LIV',
      badgeStyle: ClubBadgeStyle.vertical,
    ),
    'arsenal-fc': ClubIdentity(
      primaryColor: '#EF0107',
      secondaryColor: '#FFFFFF',
      accentColor: '#FFD700',
      symbolType: ClubSymbolType.abstractChevron,
      shortCode: 'ARS',
      badgeStyle: ClubBadgeStyle.vertical,
    ),
    'tottenham-hotspur': ClubIdentity(
      primaryColor: '#132257',
      secondaryColor: '#FFFFFF',
      accentColor: '#C0C0C0',
      symbolType: ClubSymbolType.abstractStar,
      shortCode: 'TOT',
      badgeStyle: ClubBadgeStyle.vertical,
    ),
    'newcastle-united': ClubIdentity(
      primaryColor: '#241F20',
      secondaryColor: '#FFFFFF',
      accentColor: '#888888',
      symbolType: ClubSymbolType.abstractShield,
      shortCode: 'NEW',
      badgeStyle: ClubBadgeStyle.vertical,
    ),
    'west-ham-united': ClubIdentity(
      primaryColor: '#7A263A',
      secondaryColor: '#1BB1E7',
      accentColor: '#FFD700',
      symbolType: ClubSymbolType.abstractCross,
      shortCode: 'WHU',
      badgeStyle: ClubBadgeStyle.vertical,
    ),
    'aston-villa': ClubIdentity(
      primaryColor: '#670E36',
      secondaryColor: '#95BFE5',
      accentColor: '#FFD700',
      symbolType: ClubSymbolType.abstractStar,
      shortCode: 'AVL',
      badgeStyle: ClubBadgeStyle.vertical,
    ),
    'everton-fc': ClubIdentity(
      primaryColor: '#003399',
      secondaryColor: '#FFFFFF',
      accentColor: '#FFD700',
      symbolType: ClubSymbolType.abstractChevron,
      shortCode: 'EVE',
      badgeStyle: ClubBadgeStyle.vertical,
    ),
    // Germany
    'bayern-munich': ClubIdentity(
      primaryColor: '#DC052D',
      secondaryColor: '#0066B2',
      accentColor: '#FFFFFF',
      symbolType: ClubSymbolType.abstractDiamond,
      shortCode: 'BAY',
      badgeStyle: ClubBadgeStyle.vertical,
    ),
    'borussia-dortmund': ClubIdentity(
      primaryColor: '#FDE100',
      secondaryColor: '#000000',
      accentColor: '#FFFFFF',
      symbolType: ClubSymbolType.abstractStripes,
      shortCode: 'BVB',
      badgeStyle: ClubBadgeStyle.horizontal,
    ),
    'rb-leipzig': ClubIdentity(
      primaryColor: '#DD0741',
      secondaryColor: '#FFFFFF',
      accentColor: '#002D5C',
      symbolType: ClubSymbolType.abstractOrb,
      shortCode: 'RBL',
      badgeStyle: ClubBadgeStyle.vertical,
    ),
    'bayer-leverkusen': ClubIdentity(
      primaryColor: '#E32221',
      secondaryColor: '#000000',
      accentColor: '#FFFFFF',
      symbolType: ClubSymbolType.abstractCross,
      shortCode: 'B04',
      badgeStyle: ClubBadgeStyle.vertical,
    ),
    'borussia-monchengladbach': ClubIdentity(
      primaryColor: '#000000',
      secondaryColor: '#FFFFFF',
      accentColor: '#1F6841',
      symbolType: ClubSymbolType.abstractDiamond,
      shortCode: 'BMG',
      badgeStyle: ClubBadgeStyle.vertical,
    ),
    // Italy
    'juventus': ClubIdentity(
      primaryColor: '#000000',
      secondaryColor: '#FFFFFF',
      accentColor: '#C0C0C0',
      symbolType: ClubSymbolType.abstractStripes,
      shortCode: 'JUV',
      badgeStyle: ClubBadgeStyle.metallic,
    ),
    'ac-milan': ClubIdentity(
      primaryColor: '#FB090B',
      secondaryColor: '#000000',
      accentColor: '#FFFFFF',
      symbolType: ClubSymbolType.abstractCross,
      shortCode: 'MIL',
      badgeStyle: ClubBadgeStyle.vertical,
    ),
    'inter-milan': ClubIdentity(
      primaryColor: '#010E80',
      secondaryColor: '#000000',
      accentColor: '#FFD700',
      symbolType: ClubSymbolType.abstractOrb,
      shortCode: 'INT',
      badgeStyle: ClubBadgeStyle.vertical,
    ),
    'as-roma': ClubIdentity(
      primaryColor: '#8E1F2F',
      secondaryColor: '#F0BC42',
      accentColor: '#FFD700',
      symbolType: ClubSymbolType.abstractFlame,
      shortCode: 'ROM',
      badgeStyle: ClubBadgeStyle.vertical,
    ),
    'napoli': ClubIdentity(
      primaryColor: '#12A0D7',
      secondaryColor: '#FFFFFF',
      accentColor: '#FFD700',
      symbolType: ClubSymbolType.abstractWaves,
      shortCode: 'NAP',
      badgeStyle: ClubBadgeStyle.radial,
    ),
    'lazio': ClubIdentity(
      primaryColor: '#87D8F7',
      secondaryColor: '#FFFFFF',
      accentColor: '#FFD700',
      symbolType: ClubSymbolType.abstractWaves,
      shortCode: 'LAZ',
      badgeStyle: ClubBadgeStyle.vertical,
    ),
    'fiorentina': ClubIdentity(
      primaryColor: '#482E92',
      secondaryColor: '#FFFFFF',
      accentColor: '#FFD700',
      symbolType: ClubSymbolType.abstractFlame,
      shortCode: 'FIO',
      badgeStyle: ClubBadgeStyle.vertical,
    ),
    // France
    'paris-saintgermain': ClubIdentity(
      primaryColor: '#004170',
      secondaryColor: '#DA020E',
      accentColor: '#FFD700',
      symbolType: ClubSymbolType.abstractOrb,
      shortCode: 'PSG',
      badgeStyle: ClubBadgeStyle.metallic,
    ),
    'psg': ClubIdentity(
      primaryColor: '#004170',
      secondaryColor: '#DA020E',
      accentColor: '#FFD700',
      symbolType: ClubSymbolType.abstractOrb,
      shortCode: 'PSG',
      badgeStyle: ClubBadgeStyle.metallic,
    ),
    'lyon': ClubIdentity(
      primaryColor: '#103889',
      secondaryColor: '#DA020E',
      accentColor: '#FFFFFF',
      symbolType: ClubSymbolType.abstractLion,
      shortCode: 'OL',
      badgeStyle: ClubBadgeStyle.vertical,
    ),
    'marseille': ClubIdentity(
      primaryColor: '#2FAEE0',
      secondaryColor: '#FFFFFF',
      accentColor: '#FFD700',
      symbolType: ClubSymbolType.abstractStar,
      shortCode: 'OM',
      badgeStyle: ClubBadgeStyle.radial,
    ),
    'monaco': ClubIdentity(
      primaryColor: '#E30613',
      secondaryColor: '#FFFFFF',
      accentColor: '#FFD700',
      symbolType: ClubSymbolType.abstractCrown,
      shortCode: 'MON',
      badgeStyle: ClubBadgeStyle.metallic,
    ),
    'lille-osc': ClubIdentity(
      primaryColor: '#E01E13',
      secondaryColor: '#FFFFFF',
      accentColor: '#002D5C',
      symbolType: ClubSymbolType.abstractOrb,
      shortCode: 'LIL',
      badgeStyle: ClubBadgeStyle.vertical,
    ),
    // Turkey
    'galatasaray': ClubIdentity(
      primaryColor: '#FDB912',
      secondaryColor: '#A90432',
      accentColor: '#FFD700',
      symbolType: ClubSymbolType.abstractStar,
      shortCode: 'GAL',
      badgeStyle: ClubBadgeStyle.vertical,
    ),
    'fenerbahce': ClubIdentity(
      primaryColor: '#FFED00',
      secondaryColor: '#00205B',
      accentColor: '#FFFFFF',
      symbolType: ClubSymbolType.abstractDiamond,
      shortCode: 'FEN',
      badgeStyle: ClubBadgeStyle.horizontal,
    ),
    'besiktas': ClubIdentity(
      primaryColor: '#000000',
      secondaryColor: '#FFFFFF',
      accentColor: '#FFD700',
      symbolType: ClubSymbolType.abstractStripes,
      shortCode: 'BJK',
      badgeStyle: ClubBadgeStyle.vertical,
    ),
    'trabzonspor': ClubIdentity(
      primaryColor: '#7B002C',
      secondaryColor: '#0072BC',
      accentColor: '#FFD700',
      symbolType: ClubSymbolType.abstractWaves,
      shortCode: 'TRA',
      badgeStyle: ClubBadgeStyle.vertical,
    ),
    // Netherlands / Portugal
    'ajax': ClubIdentity(
      primaryColor: '#D2122E',
      secondaryColor: '#FFFFFF',
      accentColor: '#FFD700',
      symbolType: ClubSymbolType.abstractOrb,
      shortCode: 'AJA',
      badgeStyle: ClubBadgeStyle.vertical,
    ),
    'psv-eindhoven': ClubIdentity(
      primaryColor: '#ED1C24',
      secondaryColor: '#FFFFFF',
      accentColor: '#FFD700',
      symbolType: ClubSymbolType.abstractStripes,
      shortCode: 'PSV',
      badgeStyle: ClubBadgeStyle.vertical,
    ),
    'feyenoord': ClubIdentity(
      primaryColor: '#FF0000',
      secondaryColor: '#FFFFFF',
      accentColor: '#000000',
      symbolType: ClubSymbolType.abstractOrb,
      shortCode: 'FEY',
      badgeStyle: ClubBadgeStyle.vertical,
    ),
    'benfica': ClubIdentity(
      primaryColor: '#FF0000',
      secondaryColor: '#FFFFFF',
      accentColor: '#FFD700',
      symbolType: ClubSymbolType.abstractWaves,
      shortCode: 'BEN',
      badgeStyle: ClubBadgeStyle.vertical,
    ),
    'fc-porto': ClubIdentity(
      primaryColor: '#003893',
      secondaryColor: '#FFFFFF',
      accentColor: '#FFD700',
      symbolType: ClubSymbolType.abstractFlame,
      shortCode: 'POR',
      badgeStyle: ClubBadgeStyle.vertical,
    ),
    'sporting-cp': ClubIdentity(
      primaryColor: '#008057',
      secondaryColor: '#FFFFFF',
      accentColor: '#FFD700',
      symbolType: ClubSymbolType.abstractLion,
      shortCode: 'SCP',
      badgeStyle: ClubBadgeStyle.vertical,
    ),
    // Scotland / Americas
    'celtic-fc': ClubIdentity(
      primaryColor: '#008050',
      secondaryColor: '#FFFFFF',
      accentColor: '#FFD700',
      symbolType: ClubSymbolType.abstractCross,
      shortCode: 'CEL',
      badgeStyle: ClubBadgeStyle.vertical,
    ),
    'rangers-fc': ClubIdentity(
      primaryColor: '#1B458F',
      secondaryColor: '#FFFFFF',
      accentColor: '#FFD700',
      symbolType: ClubSymbolType.abstractStar,
      shortCode: 'RAN',
      badgeStyle: ClubBadgeStyle.vertical,
    ),
    'river-plate': ClubIdentity(
      primaryColor: '#FFFFFF',
      secondaryColor: '#ED1C24',
      accentColor: '#FFD700',
      symbolType: ClubSymbolType.abstractWaves,
      shortCode: 'RIV',
      badgeStyle: ClubBadgeStyle.horizontal,
    ),
    'boca-juniors': ClubIdentity(
      primaryColor: '#003087',
      secondaryColor: '#FCB131',
      accentColor: '#FFFFFF',
      symbolType: ClubSymbolType.abstractWaves,
      shortCode: 'BOC',
      badgeStyle: ClubBadgeStyle.horizontal,
    ),
    'flamengo': ClubIdentity(
      primaryColor: '#C3281E',
      secondaryColor: '#000000',
      accentColor: '#FFFFFF',
      symbolType: ClubSymbolType.abstractStripes,
      shortCode: 'FLA',
      badgeStyle: ClubBadgeStyle.vertical,
    ),
    'palmeiras': ClubIdentity(
      primaryColor: '#006437',
      secondaryColor: '#FFFFFF',
      accentColor: '#FFD700',
      symbolType: ClubSymbolType.abstractDiamond,
      shortCode: 'PAL',
      badgeStyle: ClubBadgeStyle.vertical,
    ),
    'santos-fc': ClubIdentity(
      primaryColor: '#FFFFFF',
      secondaryColor: '#000000',
      accentColor: '#FFD700',
      symbolType: ClubSymbolType.abstractOrb,
      shortCode: 'SAN',
      badgeStyle: ClubBadgeStyle.horizontal,
    ),
    'corinthians': ClubIdentity(
      primaryColor: '#000000',
      secondaryColor: '#FFFFFF',
      accentColor: '#FFD700',
      symbolType: ClubSymbolType.abstractOrb,
      shortCode: 'COR',
      badgeStyle: ClubBadgeStyle.vertical,
    ),
    'inter-miami': ClubIdentity(
      primaryColor: '#F7B5CD',
      secondaryColor: '#000000',
      accentColor: '#FFFFFF',
      symbolType: ClubSymbolType.abstractWaves,
      shortCode: 'MIA',
      badgeStyle: ClubBadgeStyle.radial,
    ),
    'la-galaxy': ClubIdentity(
      primaryColor: '#00245D',
      secondaryColor: '#FFD200',
      accentColor: '#FFFFFF',
      symbolType: ClubSymbolType.abstractStar,
      shortCode: 'LAG',
      badgeStyle: ClubBadgeStyle.vertical,
    ),
    // Middle East / Asia / Africa — abstract defaults
    'al-hilal': ClubIdentity(
      primaryColor: '#004AAC',
      secondaryColor: '#FFFFFF',
      accentColor: '#FFD700',
      symbolType: ClubSymbolType.abstractOrb,
      shortCode: 'HIL',
      badgeStyle: ClubBadgeStyle.metallic,
    ),
    'al-nassr': ClubIdentity(
      primaryColor: '#FEDC00',
      secondaryColor: '#0E4D92',
      accentColor: '#FFFFFF',
      symbolType: ClubSymbolType.abstractStar,
      shortCode: 'NSR',
      badgeStyle: ClubBadgeStyle.vertical,
    ),
    'al-ahli': ClubIdentity(
      primaryColor: '#00783E',
      secondaryColor: '#FFFFFF',
      accentColor: '#FFD700',
      symbolType: ClubSymbolType.abstractStar,
      shortCode: 'AHL',
      badgeStyle: ClubBadgeStyle.vertical,
    ),
    'al-ahly-cairo': ClubIdentity(
      primaryColor: '#E60012',
      secondaryColor: '#FFFFFF',
      accentColor: '#FFD700',
      symbolType: ClubSymbolType.abstractWaves,
      shortCode: 'AHL',
      badgeStyle: ClubBadgeStyle.vertical,
    ),
  };
}
