"""Club name aliases and legal-safe badge metadata for top clubs."""

from .normalize import slugify

# Canonical club name aliases (SoFIFA / Kaggle variants → standard name)
CLUB_ALIASES: dict[str, str] = {
    'barcelona': 'FC Barcelona',
    'fc barcelona': 'FC Barcelona',
    'real madrid': 'Real Madrid',
    'real madrid cf': 'Real Madrid',
    'atletico madrid': 'Atletico Madrid',
    'atlético madrid': 'Atletico Madrid',
    'manchester united': 'Manchester United',
    'manchester city': 'Manchester City',
    'liverpool': 'Liverpool FC',
    'liverpool fc': 'Liverpool FC',
    'chelsea': 'Chelsea FC',
    'chelsea fc': 'Chelsea FC',
    'arsenal': 'Arsenal FC',
    'arsenal fc': 'Arsenal FC',
    'tottenham': 'Tottenham Hotspur',
    'tottenham hotspur': 'Tottenham Hotspur',
    'bayern munich': 'Bayern Munich',
    'fc bayern münchen': 'Bayern Munich',
    'borussia dortmund': 'Borussia Dortmund',
    'juventus': 'Juventus',
    'ac milan': 'AC Milan',
    'inter': 'Inter Milan',
    'internazionale': 'Inter Milan',
    'inter milan': 'Inter Milan',
    'as roma': 'AS Roma',
    'napoli': 'Napoli',
    'ssc napoli': 'Napoli',
    'paris saint-germain': 'Paris Saint-Germain',
    'paris sg': 'Paris Saint-Germain',
    'psg': 'Paris Saint-Germain',
    'olympique lyonnais': 'Lyon',
    'olympique de marseille': 'Marseille',
    'ajax': 'Ajax',
    'afc ajax': 'Ajax',
    'benfica': 'Benfica',
    'sl benfica': 'Benfica',
    'porto': 'FC Porto',
    'fc porto': 'FC Porto',
    'sporting cp': 'Sporting CP',
    'celtic': 'Celtic FC',
    'rangers': 'Rangers FC',
    'galatasaray': 'Galatasaray',
    'fenerbahce': 'Fenerbahce',
    'fenerbahçe': 'Fenerbahce',
    'besiktas': 'Besiktas',
    'beşiktaş': 'Besiktas',
    'trabzonspor': 'Trabzonspor',
}

KNOWN_BADGES: dict[str, dict[str, str]] = {
    'FC Barcelona': {
        'badge_primary_color': '#A50044',
        'badge_secondary_color': '#004D98',
        'badge_initials': 'BAR',
        'badge_gradient_style': 'vertical',
        'short_name': 'Barcelona',
        'country_code': 'ES',
    },
    'Real Madrid': {
        'badge_primary_color': '#FEBE10',
        'badge_secondary_color': '#FFFFFF',
        'badge_initials': 'RMA',
        'badge_gradient_style': 'horizontal',
        'short_name': 'Real Madrid',
        'country_code': 'ES',
    },
    'Chelsea FC': {
        'badge_primary_color': '#034694',
        'badge_secondary_color': '#FFFFFF',
        'badge_initials': 'CHE',
        'badge_gradient_style': 'horizontal',
        'short_name': 'Chelsea',
        'country_code': 'GB',
    },
    'Manchester United': {
        'badge_primary_color': '#DA291C',
        'badge_secondary_color': '#FBE122',
        'badge_initials': 'MUN',
        'badge_gradient_style': 'vertical',
        'short_name': 'Man United',
        'country_code': 'GB',
    },
    'Bayern Munich': {
        'badge_primary_color': '#DC052D',
        'badge_secondary_color': '#0066B2',
        'badge_initials': 'BAY',
        'badge_gradient_style': 'vertical',
        'short_name': 'Bayern',
        'country_code': 'DE',
    },
    'Juventus': {
        'badge_primary_color': '#000000',
        'badge_secondary_color': '#FFFFFF',
        'badge_initials': 'JUV',
        'badge_gradient_style': 'horizontal',
        'short_name': 'Juventus',
        'country_code': 'IT',
    },
    'Arsenal FC': {
        'badge_primary_color': '#EF0107',
        'badge_secondary_color': '#FFFFFF',
        'badge_initials': 'ARS',
        'badge_gradient_style': 'vertical',
        'short_name': 'Arsenal',
        'country_code': 'GB',
    },
    'Liverpool FC': {
        'badge_primary_color': '#C8102E',
        'badge_secondary_color': '#FFFFFF',
        'badge_initials': 'LIV',
        'badge_gradient_style': 'vertical',
        'short_name': 'Liverpool',
        'country_code': 'GB',
    },
    'Paris Saint-Germain': {
        'badge_primary_color': '#004170',
        'badge_secondary_color': '#DA020E',
        'badge_initials': 'PSG',
        'badge_gradient_style': 'horizontal',
        'short_name': 'PSG',
        'country_code': 'FR',
    },
    'Galatasaray': {
        'badge_primary_color': '#FDB912',
        'badge_secondary_color': '#A90432',
        'badge_initials': 'GAL',
        'badge_gradient_style': 'vertical',
        'short_name': 'Galatasaray',
        'country_code': 'TR',
    },
    'Fenerbahce': {
        'badge_primary_color': '#FFED00',
        'badge_secondary_color': '#00205B',
        'badge_initials': 'FEN',
        'badge_gradient_style': 'horizontal',
        'short_name': 'Fenerbahce',
        'country_code': 'TR',
    },
    'Besiktas': {
        'badge_primary_color': '#000000',
        'badge_secondary_color': '#FFFFFF',
        'badge_initials': 'BJK',
        'badge_gradient_style': 'vertical',
        'short_name': 'Besiktas',
        'country_code': 'TR',
    },
    'Atletico Madrid': {
        'badge_primary_color': '#CB3524',
        'badge_secondary_color': '#FFFFFF',
        'badge_initials': 'ATM',
        'badge_gradient_style': 'vertical',
        'short_name': 'Atletico',
        'country_code': 'ES',
    },
    'Sevilla FC': {
        'badge_primary_color': '#FFFFFF',
        'badge_secondary_color': '#D50000',
        'badge_initials': 'SEV',
        'badge_gradient_style': 'horizontal',
        'short_name': 'Sevilla',
        'country_code': 'ES',
    },
    'Valencia CF': {
        'badge_primary_color': '#EE3524',
        'badge_secondary_color': '#000000',
        'badge_initials': 'VAL',
        'badge_gradient_style': 'vertical',
        'short_name': 'Valencia',
        'country_code': 'ES',
    },
    'Manchester City': {
        'badge_primary_color': '#6CABDD',
        'badge_secondary_color': '#FFFFFF',
        'badge_initials': 'MCI',
        'badge_gradient_style': 'vertical',
        'short_name': 'Man City',
        'country_code': 'GB',
    },
    'Tottenham Hotspur': {
        'badge_primary_color': '#132257',
        'badge_secondary_color': '#FFFFFF',
        'badge_initials': 'TOT',
        'badge_gradient_style': 'vertical',
        'short_name': 'Tottenham',
        'country_code': 'GB',
    },
    'Newcastle United': {
        'badge_primary_color': '#241F20',
        'badge_secondary_color': '#FFFFFF',
        'badge_initials': 'NEW',
        'badge_gradient_style': 'vertical',
        'short_name': 'Newcastle',
        'country_code': 'GB',
    },
    'West Ham United': {
        'badge_primary_color': '#7A263A',
        'badge_secondary_color': '#1BB1E7',
        'badge_initials': 'WHU',
        'badge_gradient_style': 'vertical',
        'short_name': 'West Ham',
        'country_code': 'GB',
    },
    'Aston Villa': {
        'badge_primary_color': '#670E36',
        'badge_secondary_color': '#95BFE5',
        'badge_initials': 'AVL',
        'badge_gradient_style': 'vertical',
        'short_name': 'Aston Villa',
        'country_code': 'GB',
    },
    'Everton FC': {
        'badge_primary_color': '#003399',
        'badge_secondary_color': '#FFFFFF',
        'badge_initials': 'EVE',
        'badge_gradient_style': 'vertical',
        'short_name': 'Everton',
        'country_code': 'GB',
    },
    'Borussia Dortmund': {
        'badge_primary_color': '#FDE100',
        'badge_secondary_color': '#000000',
        'badge_initials': 'BVB',
        'badge_gradient_style': 'vertical',
        'short_name': 'Dortmund',
        'country_code': 'DE',
    },
    'RB Leipzig': {
        'badge_primary_color': '#DD0741',
        'badge_secondary_color': '#FFFFFF',
        'badge_initials': 'RBL',
        'badge_gradient_style': 'vertical',
        'short_name': 'Leipzig',
        'country_code': 'DE',
    },
    'Bayer Leverkusen': {
        'badge_primary_color': '#E32221',
        'badge_secondary_color': '#000000',
        'badge_initials': 'B04',
        'badge_gradient_style': 'vertical',
        'short_name': 'Leverkusen',
        'country_code': 'DE',
    },
    'Borussia Mönchengladbach': {
        'badge_primary_color': '#000000',
        'badge_secondary_color': '#FFFFFF',
        'badge_initials': 'BMG',
        'badge_gradient_style': 'vertical',
        'short_name': 'Gladbach',
        'country_code': 'DE',
    },
    'AC Milan': {
        'badge_primary_color': '#FB090B',
        'badge_secondary_color': '#000000',
        'badge_initials': 'MIL',
        'badge_gradient_style': 'vertical',
        'short_name': 'AC Milan',
        'country_code': 'IT',
    },
    'Inter Milan': {
        'badge_primary_color': '#010E80',
        'badge_secondary_color': '#000000',
        'badge_initials': 'INT',
        'badge_gradient_style': 'vertical',
        'short_name': 'Inter',
        'country_code': 'IT',
    },
    'AS Roma': {
        'badge_primary_color': '#8E1F2F',
        'badge_secondary_color': '#F0BC42',
        'badge_initials': 'ROM',
        'badge_gradient_style': 'vertical',
        'short_name': 'Roma',
        'country_code': 'IT',
    },
    'Napoli': {
        'badge_primary_color': '#12A0D7',
        'badge_secondary_color': '#FFFFFF',
        'badge_initials': 'NAP',
        'badge_gradient_style': 'vertical',
        'short_name': 'Napoli',
        'country_code': 'IT',
    },
    'Lazio': {
        'badge_primary_color': '#87D8F7',
        'badge_secondary_color': '#FFFFFF',
        'badge_initials': 'LAZ',
        'badge_gradient_style': 'vertical',
        'short_name': 'Lazio',
        'country_code': 'IT',
    },
    'Fiorentina': {
        'badge_primary_color': '#482E92',
        'badge_secondary_color': '#FFFFFF',
        'badge_initials': 'FIO',
        'badge_gradient_style': 'vertical',
        'short_name': 'Fiorentina',
        'country_code': 'IT',
    },
    'Lyon': {
        'badge_primary_color': '#103889',
        'badge_secondary_color': '#DA020E',
        'badge_initials': 'OL',
        'badge_gradient_style': 'vertical',
        'short_name': 'Lyon',
        'country_code': 'FR',
    },
    'Marseille': {
        'badge_primary_color': '#2FAEE0',
        'badge_secondary_color': '#FFFFFF',
        'badge_initials': 'OM',
        'badge_gradient_style': 'vertical',
        'short_name': 'Marseille',
        'country_code': 'FR',
    },
    'Monaco': {
        'badge_primary_color': '#E30613',
        'badge_secondary_color': '#FFFFFF',
        'badge_initials': 'MON',
        'badge_gradient_style': 'vertical',
        'short_name': 'Monaco',
        'country_code': 'FR',
    },
    'Lille OSC': {
        'badge_primary_color': '#E01E13',
        'badge_secondary_color': '#FFFFFF',
        'badge_initials': 'LIL',
        'badge_gradient_style': 'vertical',
        'short_name': 'Lille',
        'country_code': 'FR',
    },
    'Ajax': {
        'badge_primary_color': '#D2122E',
        'badge_secondary_color': '#FFFFFF',
        'badge_initials': 'AJA',
        'badge_gradient_style': 'vertical',
        'short_name': 'Ajax',
        'country_code': 'NL',
    },
    'PSV Eindhoven': {
        'badge_primary_color': '#ED1C24',
        'badge_secondary_color': '#FFFFFF',
        'badge_initials': 'PSV',
        'badge_gradient_style': 'vertical',
        'short_name': 'PSV',
        'country_code': 'NL',
    },
    'Feyenoord': {
        'badge_primary_color': '#FF0000',
        'badge_secondary_color': '#FFFFFF',
        'badge_initials': 'FEY',
        'badge_gradient_style': 'vertical',
        'short_name': 'Feyenoord',
        'country_code': 'NL',
    },
    'Benfica': {
        'badge_primary_color': '#FF0000',
        'badge_secondary_color': '#FFFFFF',
        'badge_initials': 'BEN',
        'badge_gradient_style': 'vertical',
        'short_name': 'Benfica',
        'country_code': 'PT',
    },
    'FC Porto': {
        'badge_primary_color': '#003893',
        'badge_secondary_color': '#FFFFFF',
        'badge_initials': 'POR',
        'badge_gradient_style': 'vertical',
        'short_name': 'Porto',
        'country_code': 'PT',
    },
    'Sporting CP': {
        'badge_primary_color': '#008057',
        'badge_secondary_color': '#FFFFFF',
        'badge_initials': 'SCP',
        'badge_gradient_style': 'vertical',
        'short_name': 'Sporting',
        'country_code': 'PT',
    },
    'Celtic FC': {
        'badge_primary_color': '#008050',
        'badge_secondary_color': '#FFFFFF',
        'badge_initials': 'CEL',
        'badge_gradient_style': 'vertical',
        'short_name': 'Celtic',
        'country_code': 'GB',
    },
    'Rangers FC': {
        'badge_primary_color': '#1B458F',
        'badge_secondary_color': '#FFFFFF',
        'badge_initials': 'RAN',
        'badge_gradient_style': 'vertical',
        'short_name': 'Rangers',
        'country_code': 'GB',
    },
    'Trabzonspor': {
        'badge_primary_color': '#7B002C',
        'badge_secondary_color': '#0072BC',
        'badge_initials': 'TRA',
        'badge_gradient_style': 'vertical',
        'short_name': 'Trabzonspor',
        'country_code': 'TR',
    },
    'River Plate': {
        'badge_primary_color': '#FFFFFF',
        'badge_secondary_color': '#ED1C24',
        'badge_initials': 'RIV',
        'badge_gradient_style': 'horizontal',
        'short_name': 'River',
        'country_code': 'AR',
    },
    'Boca Juniors': {
        'badge_primary_color': '#003087',
        'badge_secondary_color': '#FCB131',
        'badge_initials': 'BOC',
        'badge_gradient_style': 'vertical',
        'short_name': 'Boca',
        'country_code': 'AR',
    },
    'Flamengo': {
        'badge_primary_color': '#C3281E',
        'badge_secondary_color': '#000000',
        'badge_initials': 'FLA',
        'badge_gradient_style': 'vertical',
        'short_name': 'Flamengo',
        'country_code': 'BR',
    },
    'Palmeiras': {
        'badge_primary_color': '#006437',
        'badge_secondary_color': '#FFFFFF',
        'badge_initials': 'PAL',
        'badge_gradient_style': 'vertical',
        'short_name': 'Palmeiras',
        'country_code': 'BR',
    },
    'Santos FC': {
        'badge_primary_color': '#FFFFFF',
        'badge_secondary_color': '#000000',
        'badge_initials': 'SAN',
        'badge_gradient_style': 'horizontal',
        'short_name': 'Santos',
        'country_code': 'BR',
    },
    'Corinthians': {
        'badge_primary_color': '#000000',
        'badge_secondary_color': '#FFFFFF',
        'badge_initials': 'COR',
        'badge_gradient_style': 'vertical',
        'short_name': 'Corinthians',
        'country_code': 'BR',
    },
    'Club America': {
        'badge_primary_color': '#FBCC17',
        'badge_secondary_color': '#00265D',
        'badge_initials': 'AME',
        'badge_gradient_style': 'vertical',
        'short_name': 'America',
        'country_code': 'MX',
    },
    'Monterrey': {
        'badge_primary_color': '#004481',
        'badge_secondary_color': '#FFFFFF',
        'badge_initials': 'MTY',
        'badge_gradient_style': 'vertical',
        'short_name': 'Monterrey',
        'country_code': 'MX',
    },
    'LA Galaxy': {
        'badge_primary_color': '#00245D',
        'badge_secondary_color': '#FFD200',
        'badge_initials': 'LAG',
        'badge_gradient_style': 'vertical',
        'short_name': 'LA Galaxy',
        'country_code': 'US',
    },
    'Inter Miami': {
        'badge_primary_color': '#F7B5CD',
        'badge_secondary_color': '#000000',
        'badge_initials': 'MIA',
        'badge_gradient_style': 'vertical',
        'short_name': 'Inter Miami',
        'country_code': 'US',
    },
    'Al Hilal': {
        'badge_primary_color': '#004AAC',
        'badge_secondary_color': '#FFFFFF',
        'badge_initials': 'HIL',
        'badge_gradient_style': 'vertical',
        'short_name': 'Al Hilal',
        'country_code': 'SA',
    },
    'Al Nassr': {
        'badge_primary_color': '#FEDC00',
        'badge_secondary_color': '#0E4D92',
        'badge_initials': 'NSR',
        'badge_gradient_style': 'vertical',
        'short_name': 'Al Nassr',
        'country_code': 'SA',
    },
    'Al Ahli': {
        'badge_primary_color': '#00783E',
        'badge_secondary_color': '#FFFFFF',
        'badge_initials': 'AHL',
        'badge_gradient_style': 'vertical',
        'short_name': 'Al Ahli',
        'country_code': 'SA',
    },
    'Shakhtar Donetsk': {
        'badge_primary_color': '#FF7800',
        'badge_secondary_color': '#000000',
        'badge_initials': 'SHA',
        'badge_gradient_style': 'vertical',
        'short_name': 'Shakhtar',
        'country_code': 'UA',
    },
    'Dynamo Kyiv': {
        'badge_primary_color': '#0457A6',
        'badge_secondary_color': '#FFFFFF',
        'badge_initials': 'DYN',
        'badge_gradient_style': 'vertical',
        'short_name': 'Dynamo',
        'country_code': 'UA',
    },
    'Red Star Belgrade': {
        'badge_primary_color': '#D6000F',
        'badge_secondary_color': '#FFFFFF',
        'badge_initials': 'RSB',
        'badge_gradient_style': 'vertical',
        'short_name': 'Red Star',
        'country_code': 'RS',
    },
    'Partizan': {
        'badge_primary_color': '#000000',
        'badge_secondary_color': '#FFFFFF',
        'badge_initials': 'PAR',
        'badge_gradient_style': 'vertical',
        'short_name': 'Partizan',
        'country_code': 'RS',
    },
    'Olympiacos': {
        'badge_primary_color': '#E30613',
        'badge_secondary_color': '#FFFFFF',
        'badge_initials': 'OLY',
        'badge_gradient_style': 'vertical',
        'short_name': 'Olympiacos',
        'country_code': 'GR',
    },
    'Panathinaikos': {
        'badge_primary_color': '#009B4B',
        'badge_secondary_color': '#FFFFFF',
        'badge_initials': 'PAO',
        'badge_gradient_style': 'vertical',
        'short_name': 'Panathinaikos',
        'country_code': 'GR',
    },
    'Copenhagen': {
        'badge_primary_color': '#0054A6',
        'badge_secondary_color': '#FFFFFF',
        'badge_initials': 'FCK',
        'badge_gradient_style': 'vertical',
        'short_name': 'Copenhagen',
        'country_code': 'DK',
    },
    'Brondby': {
        'badge_primary_color': '#FFDD00',
        'badge_secondary_color': '#0066B3',
        'badge_initials': 'BIF',
        'badge_gradient_style': 'vertical',
        'short_name': 'Brondby',
        'country_code': 'DK',
    },
    'Anderlecht': {
        'badge_primary_color': '#4B0082',
        'badge_secondary_color': '#FFFFFF',
        'badge_initials': 'AND',
        'badge_gradient_style': 'vertical',
        'short_name': 'Anderlecht',
        'country_code': 'BE',
    },
    'Club Brugge': {
        'badge_primary_color': '#0080C8',
        'badge_secondary_color': '#000000',
        'badge_initials': 'BRU',
        'badge_gradient_style': 'vertical',
        'short_name': 'Club Brugge',
        'country_code': 'BE',
    },
    'Basel': {
        'badge_primary_color': '#FF0000',
        'badge_secondary_color': '#0000FF',
        'badge_initials': 'BAS',
        'badge_gradient_style': 'vertical',
        'short_name': 'Basel',
        'country_code': 'CH',
    },
    'Young Boys': {
        'badge_primary_color': '#FFDD00',
        'badge_secondary_color': '#000000',
        'badge_initials': 'YB',
        'badge_gradient_style': 'vertical',
        'short_name': 'Young Boys',
        'country_code': 'CH',
    },
    'Salzburg': {
        'badge_primary_color': '#E30613',
        'badge_secondary_color': '#FFFFFF',
        'badge_initials': 'RBS',
        'badge_gradient_style': 'vertical',
        'short_name': 'Salzburg',
        'country_code': 'AT',
    },
    'Rapid Vienna': {
        'badge_primary_color': '#007A33',
        'badge_secondary_color': '#FFFFFF',
        'badge_initials': 'RAP',
        'badge_gradient_style': 'vertical',
        'short_name': 'Rapid',
        'country_code': 'AT',
    },
    'Sparta Prague': {
        'badge_primary_color': '#8B002E',
        'badge_secondary_color': '#FFFFFF',
        'badge_initials': 'SPA',
        'badge_gradient_style': 'vertical',
        'short_name': 'Sparta',
        'country_code': 'CZ',
    },
    'Slavia Prague': {
        'badge_primary_color': '#E30613',
        'badge_secondary_color': '#FFFFFF',
        'badge_initials': 'SLA',
        'badge_gradient_style': 'vertical',
        'short_name': 'Slavia',
        'country_code': 'CZ',
    },
    'Legia Warsaw': {
        'badge_primary_color': '#007A33',
        'badge_secondary_color': '#FFFFFF',
        'badge_initials': 'LEG',
        'badge_gradient_style': 'vertical',
        'short_name': 'Legia',
        'country_code': 'PL',
    },
    'Steaua Bucharest': {
        'badge_primary_color': '#0066CC',
        'badge_secondary_color': '#CC0000',
        'badge_initials': 'STE',
        'badge_gradient_style': 'vertical',
        'short_name': 'Steaua',
        'country_code': 'RO',
    },
    'CFR Cluj': {
        'badge_primary_color': '#FF6600',
        'badge_secondary_color': '#000000',
        'badge_initials': 'CFR',
        'badge_gradient_style': 'vertical',
        'short_name': 'CFR Cluj',
        'country_code': 'RO',
    },
    'Dinamo Zagreb': {
        'badge_primary_color': '#0057B8',
        'badge_secondary_color': '#FFFFFF',
        'badge_initials': 'DIN',
        'badge_gradient_style': 'vertical',
        'short_name': 'Dinamo',
        'country_code': 'HR',
    },
    'Hajduk Split': {
        'badge_primary_color': '#FFFFFF',
        'badge_secondary_color': '#004B87',
        'badge_initials': 'HAJ',
        'badge_gradient_style': 'horizontal',
        'short_name': 'Hajduk',
        'country_code': 'HR',
    },
    'Malmo FF': {
        'badge_primary_color': '#79BFEF',
        'badge_secondary_color': '#FFFFFF',
        'badge_initials': 'MFF',
        'badge_gradient_style': 'vertical',
        'short_name': 'Malmo',
        'country_code': 'SE',
    },
    'AIK': {
        'badge_primary_color': '#000000',
        'badge_secondary_color': '#FFEC00',
        'badge_initials': 'AIK',
        'badge_gradient_style': 'vertical',
        'short_name': 'AIK',
        'country_code': 'SE',
    },
    'Rosenborg': {
        'badge_primary_color': '#000000',
        'badge_secondary_color': '#FFFFFF',
        'badge_initials': 'RBK',
        'badge_gradient_style': 'vertical',
        'short_name': 'Rosenborg',
        'country_code': 'NO',
    },
    'Molde FK': {
        'badge_primary_color': '#0054A0',
        'badge_secondary_color': '#FFFFFF',
        'badge_initials': 'MOL',
        'badge_gradient_style': 'vertical',
        'short_name': 'Molde',
        'country_code': 'NO',
    },
    'HJK Helsinki': {
        'badge_primary_color': '#0066CC',
        'badge_secondary_color': '#FFFFFF',
        'badge_initials': 'HJK',
        'badge_gradient_style': 'vertical',
        'short_name': 'HJK',
        'country_code': 'FI',
    },
    'Qarabag FK': {
        'badge_primary_color': '#000000',
        'badge_secondary_color': '#FFFFFF',
        'badge_initials': 'QAR',
        'badge_gradient_style': 'vertical',
        'short_name': 'Qarabag',
        'country_code': 'AZ',
    },
    'APOEL': {
        'badge_primary_color': '#FFD700',
        'badge_secondary_color': '#004799',
        'badge_initials': 'APO',
        'badge_gradient_style': 'vertical',
        'short_name': 'APOEL',
        'country_code': 'CY',
    },
    'Omonia': {
        'badge_primary_color': '#007A33',
        'badge_secondary_color': '#FFFFFF',
        'badge_initials': 'OMO',
        'badge_gradient_style': 'vertical',
        'short_name': 'Omonia',
        'country_code': 'CY',
    },
    'Maccabi Tel Aviv': {
        'badge_primary_color': '#FEDD00',
        'badge_secondary_color': '#004899',
        'badge_initials': 'MTA',
        'badge_gradient_style': 'vertical',
        'short_name': 'Maccabi TA',
        'country_code': 'IL',
    },
    'Maccabi Haifa': {
        'badge_primary_color': '#007A33',
        'badge_secondary_color': '#FFFFFF',
        'badge_initials': 'MHA',
        'badge_gradient_style': 'vertical',
        'short_name': 'Maccabi HA',
        'country_code': 'IL',
    },
    'Sydney FC': {
        'badge_primary_color': '#88C5EE',
        'badge_secondary_color': '#FFFFFF',
        'badge_initials': 'SYD',
        'badge_gradient_style': 'vertical',
        'short_name': 'Sydney',
        'country_code': 'AU',
    },
    'Melbourne City': {
        'badge_primary_color': '#6CACDE',
        'badge_secondary_color': '#FFFFFF',
        'badge_initials': 'MCY',
        'badge_gradient_style': 'vertical',
        'short_name': 'Melbourne',
        'country_code': 'AU',
    },
    'Urawa Red Diamonds': {
        'badge_primary_color': '#E60012',
        'badge_secondary_color': '#FFFFFF',
        'badge_initials': 'URA',
        'badge_gradient_style': 'vertical',
        'short_name': 'Urawa',
        'country_code': 'JP',
    },
    'Kashima Antlers': {
        'badge_primary_color': '#E60012',
        'badge_secondary_color': '#0055A4',
        'badge_initials': 'KAS',
        'badge_gradient_style': 'vertical',
        'short_name': 'Kashima',
        'country_code': 'JP',
    },
    'Guangzhou FC': {
        'badge_primary_color': '#E60012',
        'badge_secondary_color': '#FFFFFF',
        'badge_initials': 'GZ',
        'badge_gradient_style': 'vertical',
        'short_name': 'Guangzhou',
        'country_code': 'CN',
    },
    'Shanghai SIPG': {
        'badge_primary_color': '#E60012',
        'badge_secondary_color': '#FFFFFF',
        'badge_initials': 'SIP',
        'badge_gradient_style': 'vertical',
        'short_name': 'SIPG',
        'country_code': 'CN',
    },
    'Ulsan HD': {
        'badge_primary_color': '#004689',
        'badge_secondary_color': '#F5A623',
        'badge_initials': 'ULS',
        'badge_gradient_style': 'vertical',
        'short_name': 'Ulsan',
        'country_code': 'KR',
    },
    'Jeonbuk Hyundai': {
        'badge_primary_color': '#006633',
        'badge_secondary_color': '#FFFFFF',
        'badge_initials': 'JHM',
        'badge_gradient_style': 'vertical',
        'short_name': 'Jeonbuk',
        'country_code': 'KR',
    },
    'Wydad AC': {
        'badge_primary_color': '#E60012',
        'badge_secondary_color': '#FFFFFF',
        'badge_initials': 'WAC',
        'badge_gradient_style': 'vertical',
        'short_name': 'Wydad',
        'country_code': 'MA',
    },
    'Raja Casablanca': {
        'badge_primary_color': '#007A33',
        'badge_secondary_color': '#FFFFFF',
        'badge_initials': 'RAJ',
        'badge_gradient_style': 'vertical',
        'short_name': 'Raja',
        'country_code': 'MA',
    },
    'Esperance Tunis': {
        'badge_primary_color': '#FFD700',
        'badge_secondary_color': '#E60012',
        'badge_initials': 'EST',
        'badge_gradient_style': 'vertical',
        'short_name': 'Esperance',
        'country_code': 'TN',
    },
    'Al Ahly Cairo': {
        'badge_primary_color': '#E60012',
        'badge_secondary_color': '#FFFFFF',
        'badge_initials': 'AHL',
        'badge_gradient_style': 'vertical',
        'short_name': 'Al Ahly',
        'country_code': 'EG',
    },
    'Kaizer Chiefs': {
        'badge_primary_color': '#FFB612',
        'badge_secondary_color': '#000000',
        'badge_initials': 'KAI',
        'badge_gradient_style': 'vertical',
        'short_name': 'Kaizer',
        'country_code': 'ZA',
    },
    'Orlando Pirates': {
        'badge_primary_color': '#000000',
        'badge_secondary_color': '#FFFFFF',
        'badge_initials': 'PIR',
        'badge_gradient_style': 'vertical',
        'short_name': 'Pirates',
        'country_code': 'ZA',
    },
}

# Legacy slugs from migration 001 seed (ETL uses slugify(name) instead).
LEGACY_CLUB_SLUGS: dict[str, str] = {
    'FC Barcelona': 'barcelona',
    'Chelsea FC': 'chelsea',
    'Paris Saint-Germain': 'psg',
}


def canonical_club_name(raw: str) -> str:
    key = raw.strip().lower()
    return CLUB_ALIASES.get(key, raw.strip())


def badge_for_club(name: str) -> dict[str, str]:
    if name in KNOWN_BADGES:
        return KNOWN_BADGES[name]

    slug = slugify(name)
    initials = ''.join(part[0] for part in name.split()[:2]).upper()[:3] or slug[:3].upper()
    hue = abs(hash(name)) % 360
    primary = f'#{hue:02x}6633'[:7]
    secondary = f'#{255 - hue % 200:02x}4422'[:7]

    return {
        'badge_primary_color': primary,
        'badge_secondary_color': secondary,
        'badge_initials': initials,
        'badge_gradient_style': 'vertical',
        'badge_accent_color': '#FFD700',
        'symbol_type': 'abstract_shield',
        'short_name': name.split()[0] if len(name) > 14 else name,
        'country_code': '',
    }


def club_record(name: str, *, is_top: bool = True) -> dict:
    meta = badge_for_club(name)
    return {
        'name': name,
        'country_code': meta.get('country_code') or None,
        'is_top_club': is_top,
        'badge_primary_color': meta['badge_primary_color'],
        'badge_secondary_color': meta['badge_secondary_color'],
        'badge_accent_color': meta.get('badge_accent_color'),
        'badge_initials': meta['badge_initials'],
        'badge_icon_type': meta.get('symbol_type', 'abstract_shield'),
        'badge_gradient_style': meta['badge_gradient_style'],
        'short_name': meta['short_name'],
        'display_name': name,
        'short_code': meta['badge_initials'],
        'league_name': meta.get('league_name'),
    }
